version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL}
      - NODE_ENV=${NODE_ENV}
      - EXECUTIONS_MODE=${EXECUTIONS_MODE}
      - QUEUE_BULL_REDIS_HOST=redis
      - DB_TYPE=${DB_TYPE}
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n_network
    env_file:
      - .env

  redis:
    image: redis:6
    container_name: n8n-redis
    restart: unless-stopped
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
